version: '3.3'

networks: 
  ntpgsql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  pgsql:
    image: postgres:latest
    restart: no
            # always
            # unless-stopped (avvia il container all'avvio del docker)
    container_name: postgresql
#    volumes:
#      - psdb-volume:/var/lib/postgresql/data (definisce i volumi dove saranno posizionate le immagini )
    networks: 
      ntpgsql:
        ipv4_address: 172.21.0.2
    ports:
      # - "6000:5432"
      - target: 5432
        published: 6000
        protocol: tcp
        mode: host
    environment:
      # - POSTGRES_USER=andr3a.giacomini@gmail.com
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alpha-shop

  pgadmin:
    image: dpage/pgadmin4
    restart: no
            # always
            # unless-stopped (avvia il container all'avvio del docker)
    container_name: pgadmin4
    networks:
      ntpgsql:
        ipv4_address: 172.21.0.3
    ports:
      # - "80:80"
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_DEFAULT_EMAIL=andr3a.giacomini@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin


volumes:
  psdb-volume:

